# Generated by Django 3.0.6 on 2020-05-29 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(blank=True, default='hotehubclient', max_length=100, null=True)),
                ('cif', models.CharField(default='00000000A', max_length=100, unique=True)),
                ('razon_social', models.CharField(choices=[('SL', 'SL'), ('SA', 'SA'), ('Autonomo', 'Autonomo'), ('SCOOP', 'SCOOP'), ('Otros', 'Otros')], default='SL', max_length=100)),
                ('marca_comercial', models.CharField(max_length=100)),
                ('nombre_fiscal', models.CharField(max_length=100)),
                ('tipo_negocio', models.CharField(choices=[('Bar', 'Bar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Ocio Nocturno', 'Ocio Nocturno'), ('Otros', 'Otros')], default='Bar', max_length=100)),
                ('tipo_via', models.CharField(max_length=100)),
                ('direccion_fiscal', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(default='Granada', max_length=100)),
                ('codigo_postal', models.CharField(max_length=100)),
                ('telefono_1', models.CharField(max_length=100)),
                ('telefono_2', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=1000)),
                ('pdf', models.CharField(max_length=1000)),
                ('qr', models.CharField(max_length=1000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email address')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_premium', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
