# Generated by Django 3.0.6 on 2020-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_negocio',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Discoteca', 'Discoteca'), ('Cafeteria', 'Cafeteria'), ('Catering', 'Catering'), ('Churreria', 'Churreria'), ('Pub', 'Pub'), ('Cerveceria', 'Cerveceria'), ('Heladeria', 'Heladeria'), ('Otros', 'Otros')], default='Bar', max_length=100),
        ),
    ]
