# Generated by Django 3.0.6 on 2020-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='frontend/static/frontend/uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr',
            field=models.ImageField(default='', upload_to='frontend/static/frontend/qr'),
        ),
    ]
