# Generated by Django 3.0.6 on 2020-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='hotehubclient', max_length=100, null=True),
        ),
    ]
