# Generated by Django 3.0.6 on 2020-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200525_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf',
            field=models.FileField(default='', upload_to='frontend/static/uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='frontend/static/updloads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
