# Generated by Django 3.0.6 on 2020-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200527_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pdf',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
