# Generated by Django 3.0.6 on 2020-05-24 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cartanegocio', max_length=100)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='producto', max_length=100)),
                ('tamanio', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=3)),
                ('precio1', models.IntegerField(default='0')),
                ('precio2', models.IntegerField(default='0')),
                ('precio3', models.IntegerField(default='0')),
                ('carta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carta.Carta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='carta.Categorias')),
            ],
        ),
    ]
