# Generated by Django 3.0.6 on 2020-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='is_altramuces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_apio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_cacahuete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_crustaceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_frutos_con_cascara',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_huevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_lacteo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_molusco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_mostaza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_pescado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_sesamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_soja',
            field=models.BooleanField(default=False),
        ),
    ]
