# Generated by Django 3.0.6 on 2020-05-25 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.CharField(default='producto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
